/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package visolate.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PARAM_DELIM = 5;
  /** RegularExpression Id. */
  int CODE_DELIM = 6;
  /** RegularExpression Id. */
  int SIGN = 7;
  /** RegularExpression Id. */
  int DIGITS = 8;
  /** RegularExpression Id. */
  int DIGIT = 9;
  /** RegularExpression Id. */
  int IN = 10;
  /** RegularExpression Id. */
  int LN = 11;
  /** RegularExpression Id. */
  int ADD = 12;
  /** RegularExpression Id. */
  int AM = 13;
  /** RegularExpression Id. */
  int COMMENT = 14;
  /** RegularExpression Id. */
  int TEXT = 15;
  /** RegularExpression Id. */
  int DIGITS2 = 16;
  /** RegularExpression Id. */
  int DIGIT2 = 17;
  /** RegularExpression Id. */
  int ALNUMS = 18;
  /** RegularExpression Id. */
  int AL = 19;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int TEXT_EXPECTED = 1;
  /** Lexical state. */
  int ALNUMS_EXPECTED = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"%\"",
    "\"*\"",
    "<SIGN>",
    "<DIGITS>",
    "<DIGIT>",
    "\"IN\"",
    "\"LN\"",
    "\"ADD\"",
    "\"AM\"",
    "\"G04\"",
    "<TEXT>",
    "<DIGITS2>",
    "<DIGIT2>",
    "<ALNUMS>",
    "<AL>",
    "\"N\"",
    "\"G00\"",
    "\"G01\"",
    "\"G02\"",
    "\"G03\"",
    "\"G36\"",
    "\"G37\"",
    "\"G54\"",
    "\"G70\"",
    "\"G71\"",
    "\"G74\"",
    "\"G75\"",
    "\"G90\"",
    "\"G91\"",
    "\"D01\"",
    "\"D02\"",
    "\"D03\"",
    "\"D\"",
    "\"X\"",
    "\"Y\"",
    "\"I\"",
    "\"J\"",
    "\".\"",
    "\"M00\"",
    "\"M01\"",
    "\"M02\"",
    "\"IC\"",
    "\"AS\"",
    "\"EB\"",
    "\"BC\"",
    "\"IS\"",
    "\"EI\"",
    "\"A\"",
    "\"B\"",
    "\"FS\"",
    "\"L\"",
    "\"T\"",
    "\"G\"",
    "\"Z\"",
    "\"M\"",
    "\"IP\"",
    "\"POS\"",
    "\"NEG\"",
    "\"LP\"",
    "\"C\"",
    "\"MOIN\"",
    "\"MOMM\"",
    "\"OF\"",
    "\"SF\"",
    "\"SR\"",
    "\",\"",
    "\"x\"",
    "\"/\"",
    "\"$\"",
  };

}
